### ISSUE TITLE
Credit original game designers

### ISSUE THREAD

**Issue by tannerkrewson** [tannerkrewson/rocketcrab#29]
For mobile web party games that are based on other games, add an optional field to credit original game designers to the game info box.

thx rocktopus 👍

**Comment by cynicaloptimist** [comment]
What do you think about making this field mandatory?

**Comment by cynicaloptimist** [comment]
i.e. mandatory fields for Game Credit and Adaptation Credit, which could be the same person.

**Game Credit**: Author of the original game
**Adaptation Credit**: Author of the software adaptation

**Comment by tannerkrewson** [comment]
added in 94acce1d375f6b24ef00f5a69dcae8e8278f0a0f let me know what you think!

**Comment by cynicaloptimist** [comment]
Looks great, thank you for adding this!

**Comment by tannerkrewson** [comment]
🎉 🎉 🎉
