### ISSUE TITLE
Android pictionary time change causes line wrap that moves screen while drawing

### ISSUE THREAD

**Issue by droarty** [tannerkrewson/rocketcrab#86]
On a Pixel 3 while drawing on pictionary, the screen jumps down then up again depending on the width of the time.   So when the time goes from 1:10 to 1:09, the latter is wider and causes the line to wrap -  "There is 1:09 minutes left to play" or whatever it says.

Great platform, just wanted to point out this annoyance.

**Comment by tannerkrewson** [comment]
which game is this referring to?

**Comment by droarty** [comment]
Sorry, mentioned the wrong name.   It was drawphone.

**Comment by droarty** [comment]
Ah, I see you have that game in a separate repo.   I will close this issue and move it there.
